packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  cpu-features: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  ssh2: false
onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - msgpackr-extract
  - cpu-features
  - ssh2
